name: 'TestApp'
description: 'Test an app'
inputs:
  test_scheme:
    required: true
    type: string
  MATCH_PASSWORD:
    required: true
    type: string
  MATCH_GITHUB_TOKEN:
    required: true
    type: string
  HEDVIG_GITHUB_APP_ID:
    required: true
    type: string
  HEDVIG_GITHUB_APP_PRIVATE_KEY:
    required: true
    type: string
  S3_ACCESS_KEY:
    required: true
    type: string
  S3_SECRET_ACCESS_KEY:
    required: true
    type: string
  SSH_CACHE_CREDENTIALS:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Clean
      run: rm -rf *
      shell: bash
    - uses: actions/checkout@v2
    - name: Download generated
      run: rsync -ra ${{ inputs.SSH_CACHE_CREDENTIALS }}:/Volumes/Cache/generated/${{ github.sha }}/ .
      shell: bash
    - name: Fetch cache
      run: rsync -raWPop ${{ inputs.SSH_CACHE_CREDENTIALS }}:/Volumes/Cache/DerivedData /Users/app/Library/Developer/Xcode/ || true
      shell: bash
    - name: Bundle install
      run: arch -arm64 sudo --preserve-env bundle install
      shell: bash
    - name: Fastlane Action
      env:
        MATCH_PASSWORD: ${{ inputs.MATCH_PASSWORD }}
        MATCH_GITHUB_TOKEN: ${{ inputs.MATCH_GITHUB_TOKEN }}
        HEDVIG_GITHUB_APP_ID: ${{ inputs.HEDVIG_GITHUB_APP_ID }}
        HEDVIG_GITHUB_APP_PRIVATE_KEY: ${{ inputs.HEDVIG_GITHUB_APP_PRIVATE_KEY }}
        S3_ACCESS_KEY: ${{ inputs.S3_ACCESS_KEY }}
        S3_SECRET_ACCESS_KEY: ${{ inputs.S3_SECRET_ACCESS_KEY }}
        FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: '180'
        FASTLANE_XCODE_LIST_TIMEOUT: '180'
        BUILD_NAME: test_${{ inputs.test_scheme }}
      run: arch -arm64 bundle exec fastlane ios test scheme:${{ inputs.test_scheme }}
      shell: bash
    - name: Upload cache
      run: rsync -raWPop /Users/app/Library/Developer/Xcode/DerivedData ${{ inputs.SSH_CACHE_CREDENTIALS }}:/Volumes/Cache || true
      shell: bash
    - name: Upload test results
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: Ugglan.xcresult
        path: fastlane/test_output/${{ inputs.test_scheme }}.xcresult
    - name: Delete build artifacts
      run: sudo rm -rf /Users/app/Library/Developer/Xcode/Archives && sudo rm -rf /Users/app/Library/Developer/Xcode/DerivedData/TestResults
      shell: bash