import ProjectDescription

let config = Config(
    compatibleXcodeVersions: ["12.3", "12.4"],
    generationOptions: [
        .xcodeProjectName("\(.projectName)"),
        .organizationName("Hedvig AB"),
        .disableAutogeneratedSchemes,
        .disableSynthesizedResourceAccessors,
    ]
)
