import ProjectDescription

let config = Config(
    compatibleXcodeVersions: ["12.0", "12.0.1", "12.2"],
    generationOptions: [
        .xcodeProjectName("\(.projectName)"),
        .organizationName("Hedvig AB"),
        .disableAutogeneratedSchemes,
        .disableSynthesizedResourceAccessors,
    ]
)
