import ProjectDescription

let config = Config(
    compatibleXcodeVersions: ["12.3"],
    generationOptions: [
        .xcodeProjectName("\(.projectName)"),
        .organizationName("Hedvig AB"),
        .disableAutogeneratedSchemes,
        .disableSynthesizedResourceAccessors,
    ]
)
