disabled_rules:
  - trailing_whitespace
  - closure_parameter_position
  - function_body_length
excluded:
  - Pods
  - Hedvig/Data/API.swift
  - Hedvig/UI/Generic/UICollectionView+ScrollViewAnimateable.swift
type_name:
  excluded: V
