included:
  - Projects
excluded:
  - 'Projects/*/Sources/Derived'
disabled_rules:
  - weak_delegate
opt_in_rules:
  - empty_count
  - explicit_init
  - closure_spacing
  - overridden_super_call
  - redundant_nil_coalescing
  - private_outlet
  - nimble_operator
  - attributes
  - operator_usage_whitespace
  - closure_end_indentation
  - first_where
  - sorted_imports
  - object_literal
  - number_separator
  - prohibited_super_call
  - fatal_error_message
line_length: 120
number_separator:
  minimum_length: 5