disabled_rules:
  - trailing_whitespace
  - closure_parameter_position
  - function_body_length
  - cyclomatic_complexity
excluded:
  - Pods
  - Src/Data/API.swift
type_name:
  excluded:
    - V
identifier_name:
  excluded:
    - id
