import ProjectDescription


let config = Config(
  compatibleXcodeVersions: ["11.4.1"],
  generationOptions: [
    .xcodeProjectName("\(.projectName)"),
    .organizationName("Hedvig AB"),
    .disableAutogeneratedSchemes
  ]
)
