---
version: 2.2.0
configurations:
  debug:
    overrides:
      IPHONEOS_DEPLOYMENT_TARGET: "9.0"
  release:
    overrides:
      IPHONEOS_DEPLOYMENT_TARGET: "9.0"
      CODE_SIGN_IDENTITY: "iPhone Distribution: Hedvig AB (AW656G5PFM)"
      "CODE_SIGN_IDENTITY[sdk=iphoneos*]": "iPhone Distribution: Hedvig AB (AW656G5PFM)"
      PROVISIONING_PROFILE_SPECIFIER: "Ugglan - AdHoc 2"
targets:
  ugglan:
    type: ":application"
    platform: ios
    sources: Src
    references:
        - sdkroot:UIKit.framework
        - location: Carthage/Build/iOS/DeviceKit.framework
        - location: Carthage/Build/iOS/Apollo.framework
        - location: Carthage/Build/iOS/ApolloSQLite.framework
        - location: Carthage/Build/iOS/ApolloWebSocket.framework
        - location: Carthage/Build/iOS/Firebase.framework
        - location: Carthage/Build/iOS/FirebaseAnalytics.framework
        - location: Carthage/Build/iOS/FirebaseCore.framework
        - location: Carthage/Build/iOS/FirebaseCoreDiagnostics.framework
        - location: Carthage/Build/iOS/FirebaseInstanceID.framework
        - location: Carthage/Build/iOS/Flow.framework
        - location: Carthage/Build/iOS/Form.framework
        - location: Carthage/Build/iOS/GoogleAppMeasurement.framework
        - location: Carthage/Build/iOS/GoogleUtilities.framework
        - location: Carthage/Build/iOS/Lottie.framework
        - location: Carthage/Build/iOS/Presentation.framework
        - location: Carthage/Build/iOS/SQLite.framework
        - location: Carthage/Build/iOS/SWXMLHash.framework
        - location: Carthage/Build/iOS/SnapKit.framework
        - location: Carthage/Build/iOS/Starscream.framework
        - location: Carthage/Build/iOS/Yams.framework
        - location: Carthage/Build/iOS/nanopb.framework
        - location: Carthage/Build/iOS/FlowFeedback.framework
        - location: Carthage/Build/iOS/UICollectionView_AnimatedScroll.framework
    configuration:
      INFOPLIST_FILE: Src/Info.plist
      IPHONEOS_DEPLOYMENT_TARGET: "9.0"
      SWIFT_VERSION: "4.2"
      PRODUCT_BUNDLE_IDENTIFIER: "com.hedvig.ugglan"
      DEVELOPMENT_TEAM: "AW656G5PFM"
      FRAMEWORK_SEARCH_PATHS:
        - $(inherited)
        - Carthage/Build/iOS
schemes:
  Debug:
    archive:
      name: ugglan.xcarchive
      reveal: true
      build_configuration: debug
    build:
      parallel: true
      build_implicit: true
      targets:
        ugglan:
          archiving_enabled: true
          running_enabled: true
          profiling_enabled: true
          testing_enabled: false
          analyzing_enabled: true
    launch:
      build_configuration: debug
      target: ugglan
      arguments: -AppleLanguages (en-GB)
      environment:
        OS_ACTIVITY_MODE: disable
  Release:
    archive:
      name: ugglan.xcarchive
      reveal: true
      build_configuration: release
    build:
      parallel: true
      build_implicit: true
      targets:
        ugglan:
          archiving_enabled: true
          running_enabled: true
          profiling_enabled: true
          testing_enabled: false
          analyzing_enabled: true
    launch:
      build_configuration: release
      target: ugglan
      arguments: -AppleLanguages (en-GB)
      environment:
        OS_ACTIVITY_MODE: disable
