import ProjectDescription
import ProjectDescriptionHelpers

let workspace = Workspace(
    name: "Ugglan",
    projects: ["Projects/*", "Dependencies/*"],
    generationOptions: .options(
        // Marks every testable in the autogenerated Ugglan-Workspace scheme as
        // parallelizable. Xcode then distributes test classes across cloned
        // simulators instead of running all 21 bundles serially on one.
        autogeneratedWorkspaceSchemes: .enabled(testingOptions: [.parallelizable]),
        lastXcodeUpgradeCheck: .init(string: "2600")
    )
)
