query TerminationSurvey($contractId: UUID!, $redirectionEnabled: Boolean!) {
  terminationSurvey(contractId: $contractId, redirectionEnabled: $redirectionEnabled) {
    options {
      ...TerminationSurveyOptionFragment
      subOptions {
        ...TerminationSurveyOptionFragment
        subOptions {
          ...TerminationSurveyOptionFragment
          subOptions {
            ...TerminationSurveyOptionFragment
          }
        }
      }
    }
    action {
      ... on TerminationFlowActionTerminateWithDate {
        minDate
        maxDate
        extraCoverage {
          ...TerminationExtraCoverageItemFragment
        }
      }
      ... on TerminationFlowActionDeleteInsurance {
        extraCoverage {
          ...TerminationExtraCoverageItemFragment
        }
      }
    }
  }
}

fragment TerminationSurveyOptionFragment on TerminationFlowSurveyOption {
  id
  title
  feedbackRequired
  suggestion {
    ...TerminationSurveyOptionSuggestionFragment
  }
  redirection {
    ...TerminationSurveyOptionRedirectionFragment
  }
}

fragment TerminationSurveyOptionRedirectionFragment on TerminationFlowSurveyOptionRedirection {
  title
  description
  type
  actionText
  image {
    url
    overlayText
  }
}

fragment TerminationSurveyOptionSuggestionFragment on TerminationFlowSurveyOptionSuggestion {
  type
  description
  url
}

fragment TerminationExtraCoverageItemFragment on TerminationFlowExtraCoverageItem {
  displayName
  displayValue
}
