# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
    lane :refresh_dsyms do
        download_dsyms
        sentry_upload_dsym
        clean_build_artifacts
    end
    
    lane :workspace_tests do
        carthage(
            command: "bootstrap",
            cache_builds: true,
            platform: "ios"
        )
        
        sh("cd ..; tuist up")
        sh("cd ..; tuist generate")
        
        schemes = [
            "Ugglan",
            "hCore",
            "hCoreUI",
            "Embark",
            "Forever",
            "Contracts",
            "Home"
        ]
        
        schemes.each { |scheme|
            scan(
                workspace: "Ugglan.xcworkspace",
                devices: ["iPhone 11 Pro"],
                disable_concurrent_testing: true,
                scheme: scheme,
                derived_data_path: "scan_derived_data"
            )
        }
        
        xchtmlreport(
          result_bundle_paths: schemes.map { |scheme| "fastlane/test_output/#{scheme}.xcresult" }
        )
    end
end
