name: "BuildWorspaceApp"
description: "Build app in workspace"

inputs:
 scheme:
   description: “Scheme”
   required: true
  path:
   description: "Path to project"
   required: true
  identifier:
   description: "Identifier for app"
   required: true

runs:
 using: "composite"
 steps:
  - uses: actions/checkout@v2
  - uses: actions/download-artifact@v2
    with:
      name: generated_files
  - uses: ./.github/actions/FastlaneAction
    with:
      lane: ios build identifier:${{ inputs.identifier }} path:${{ inputs.project-path }} scheme:${{ inputs.lane }}
  - name: Upload app
    uses: actions/upload-artifact@v2
    with:
      name: ${{ inputs.lane }}.ipa
      path: fastlane/build_output/${{ inputs.lane }}.ipa