name: BuildWorkspaceApp

defaults:
  run:
    shell: bash -ieo pipefail {0}

on:
  workflow_call:
    inputs:
      lane:
        required: true
        type: string
      name:
        required: true
        type: string
      path:
        required: true
        type: string
      test_scheme:
        required: true
        type: string
    secrets:
      MATCH_PASSWORD:
        required: true
      MATCH_GITHUB_TOKEN:
        required: true
      HEDVIG_GITHUB_APP_ID:
        required: true
      HEDVIG_GITHUB_APP_PRIVATE_KEY:
        required: true
      S3_ACCESS_KEY:
        required: true
      S3_SECRET_ACCESS_KEY:
        required: true

jobs:
  should_run:
    runs-on: ubuntu-latest
      
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}

    steps:
      - uses: actions/checkout@v2
      - name: Should run
        id: should_run
        uses: ./.github/actions/should-run
        with:
          path: ${{ inputs.path }}

  build:
    runs-on: self-hosted
    timeout-minutes: 30
    needs: should_run
    if: needs.should_run.outputs.should_run == 'true'

    steps:
      - name: Should run
        id: should_run
        uses: ./.github/actions/should-run
        with:
          path: ${{ inputs.path }}
      - uses: actions/checkout@v2
        if: steps.should_run.outputs.should_run == 'true'
      - uses: actions/download-artifact@v2
        with:
          name: generated_files
      - name: Bundle install
        run: arch -arm64 sudo --preserve-env bundle install
      - name: Fastlane Action
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GITHUB_TOKEN: ${{ secrets.MATCH_GITHUB_TOKEN }}
          HEDVIG_GITHUB_APP_ID: ${{ secrets.HEDVIG_GITHUB_APP_ID }}
          HEDVIG_GITHUB_APP_PRIVATE_KEY: ${{ secrets.HEDVIG_GITHUB_APP_PRIVATE_KEY }}
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: '180'
          FASTLANE_XCODE_LIST_TIMEOUT: '180'
          GITHUB_JOB: build_${{ inputs.name }}
        run: arch -arm64 bundle exec fastlane ${{ inputs.lane }}
      - name: Upload app
        uses: actions/upload-artifact@v2
        with:
          name: ${{ inputs.name }}.ipa
          path: fastlane/build_output/${{ inputs.name }}.ipa

  test:
    needs: build
    runs-on: self-hosted
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: generated_files
      - name: Bundle install
        run: arch -arm64 sudo --preserve-env bundle install
      - name: Fastlane Action
        env:
          FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: '180'
          FASTLANE_XCODE_LIST_TIMEOUT: '180'
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          HEDVIG_GITHUB_APP_ID: ${{ secrets.HEDVIG_GITHUB_APP_ID }}
          HEDVIG_GITHUB_APP_PRIVATE_KEY: ${{ secrets.HEDVIG_GITHUB_APP_PRIVATE_KEY }}
          GITHUB_JOB: test_${{ inputs.scheme }}
        run: arch -arm64 bundle exec fastlane ios test scheme:${{ inputs.test_scheme }}
      - name: Upload test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: Ugglan.xcresult
          path: fastlane/test_output/${{ inputs.test_scheme }}.xcresult

