name: BuildWorkspaceApp

defaults:
  run:
    shell: bash -ieo pipefail {0}

on:
  workflow_call:
    inputs:
      lane:
        required: true
        type: string
      name:
        required: true
        type: string
      path:
        required: true
        type: string
    secrets:
      MATCH_PASSWORD:
        required: true
      MATCH_GITHUB_TOKEN:
        required: true
      HEDVIG_GITHUB_APP_ID:
        required: true
      HEDVIG_GITHUB_APP_PRIVATE_KEY:
        required: true
      S3_ACCESS_KEY:
        required: true
      S3_SECRET_ACCESS_KEY:
        required: true

jobs:
  should_run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v11.7
        with:
          files: |
            ${{ inputs.path }}
            Projects/Dependencies
            Projects/hCore
            Projects/hCoreUI
            Projects/hGraphQL

  build:
    needs: should_run
    runs-on: self-hosted
    timeout-minutes: 30
    if: ${{ job.should_run.steps.changed-files.outputs.any_changed == 'true' }}

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/download-artifact@v2
        with:
          name: generated_files
      - name: Bundle install
        run: arch -arm64 sudo --preserve-env bundle install
      - name: Fastlane Action
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GITHUB_TOKEN: ${{ secrets.MATCH_GITHUB_TOKEN }}
          HEDVIG_GITHUB_APP_ID: ${{ secrets.HEDVIG_GITHUB_APP_ID }}
          HEDVIG_GITHUB_APP_PRIVATE_KEY: ${{ secrets.HEDVIG_GITHUB_APP_PRIVATE_KEY }}
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: '180'
          FASTLANE_XCODE_LIST_TIMEOUT: '180'
          GITHUB_JOB: build_${{ inputs.name }}
        run: arch -arm64 bundle exec fastlane ${{ inputs.lane }}
      - name: Upload app
        uses: actions/upload-artifact@v2
        with:
          name: ${{ inputs.name }}.ipa
          path: fastlane/build_output/${{ inputs.name }}.ipa

