name: CreateRelease

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["App Store Connect Submit"]
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 # v1
        with:
          xcode-version: latest-stable
      - name: Post checkout pre
        run: scripts/install-tuist.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Post checkout post
        run: scripts/post-checkout.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Version
        id: get-version
        run: cd Projects/App && echo version=$(agvtool what-marketing-version -terse1) >> "$GITHUB_OUTPUT"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get-version.outputs.version }}
          release_name: Release-${{ steps.get-version.outputs.version }}
          body: Release
          draft: false
          prerelease: false
