name: CreateRelease

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.0.0"
      - name: Setup .netrc file
        run: |
          echo -e "machine maven.pkg.github.com\n  login ${{ secrets.HEDVIG_GITHUB_PACKAGES_USER }}\n  password ${{ secrets.HEDVIG_GITHUB_PACKAGES_TOKEN }}" > ~/.netrc
      - name: Post checkout pre
        run: PATH=$PATH":$GITHUB_WORKSPACE/.tuist-bin" scripts/post-checkout-git-actions-pre.sh
      - name: Tuist generate
        uses: tuist/tuist-action@0.13.0
        with:
          command: 'generate'
          arguments: ''
      - name: Post checkout post
        run: PATH=$PATH":$GITHUB_WORKSPACE/.tuist-bin" scripts/post-checkout-git-actions-post.sh
      - name: Get Version
        id: get-version
        run: cd Projects/App && echo version=$(agvtool what-marketing-version -terse1) >> "$GITHUB_OUTPUT"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get-version.outputs.version }}
          release_name: Release-${{ steps.get-version.outputs.version }}
          body: Release
          draft: false
          prerelease: false
