name: CreateRelease

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: macos-13

    steps:
      - name: Get Version
        run: cd Projects/App && echo "version={xcrun agvtool what-marketing-version}" >> "$GITHUB_ENV"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ version }}
          release_name: Release-${{ version }}
          body: Release
          draft: false
          prerelease: false
