name: CreateRelease

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Post checkout pre
        run: scripts/install-tuist.sh
      - name: Post checkout post
        run: scripts/post-checkout.sh
      - name: Get Version
        id: get-version
        run: cd Projects/App && echo version=$(agvtool what-marketing-version -terse1) >> "$GITHUB_OUTPUT"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get-version.outputs.version }}
          release_name: Release-${{ steps.get-version.outputs.version }}
          body: Release
          draft: false
          prerelease: false
