name: ProductionDeploy

on:
  workflow_dispatch:
    inputs:
      versionNumber:
        description: 'Version number'
        required: true

jobs:
  deploy:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: XCode Select
      run: sudo xcode-select -s /Applications/Xcode_11.6.app
    - name: Cache RubyGems
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: ${{ runner.os }}-gem-
    - name: Install Tuist
      run: bash <(curl -Ls https://install.tuist.io)
    - name: Fastlane Action
      uses: maierj/fastlane-action@v1.4.0
      env:
        FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
        FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        MATCH_GITHUB_TOKEN: ${{ secrets.MATCH_GITHUB_TOKEN }}
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
       lane: ios production_upload version_number:${{ github.event.inputs.versionNumber }}
