name: ProductionDeploy

on:
  workflow_dispatch:
    inputs:
      versionNumber:
        description: 'Version number'
        required: true

jobs:
  deploy:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Trigger DSYM
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: Upload DSYM
        token: ${{ secrets.MATCH_GITHUB_TOKEN }}
    - name: XCode Select
      run: sudo xcode-select -s /Applications/Xcode_12.3.app
    - name: Install Tuist
      run: bash <(curl -Ls https://install.tuist.io)
    - run: brew install getsentry/tools/sentry-cli
    - name: Fastlane Action
      uses: maierj/fastlane-action@v1.4.0
      env:
        APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
        APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
        APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        MATCH_GITHUB_TOKEN: ${{ secrets.MATCH_GITHUB_TOKEN }}
        GITHUB_ACCESS_TOKEN: ${{ secrets.MATCH_GITHUB_TOKEN }}
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_PROJECT_SLUG: ${{ secrets.SENTRY_PROJECT_SLUG }}
        SENTRY_ORG_SLUG: ${{ secrets.SENTRY_ORG_SLUG }}
      with:
       lane: ios production_upload version_number:${{ github.event.inputs.versionNumber }}
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: 'Update app version to ${{ github.event.inputs.versionNumber }}'
        title: 'Update app version to ${{ github.event.inputs.versionNumber }}'
        body: 'This PR was created automatically by the ProductionDeploy action, merge this so that the repo has a matching app version to what will be deployed to App Store.'
        branch: 'update-app-version/${{ github.event.inputs.versionNumber }}'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.versionNumber }}
        release_name: Release-${{ github.event.inputs.versionNumber }}
        body: Release
        draft: false
        prerelease: false
