name: ProductionDeploy

on:
  workflow_dispatch:
    inputs:
      versionNumber:
        description: 'Version number'
        required: true

jobs:
  deploy:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: XCode Select
      run: sudo xcode-select -s /Applications/Xcode_12.app
    - name: Set XCODE_XCCONFIG_FILE
      run: echo ::set-env name=XCODE_XCCONFIG_FILE::$(echo $GITHUB_WORKSPACE/Carthage-Xcode12-Workaround.xcconfig)
    - name: Install Tuist
      run: bash <(curl -Ls https://install.tuist.io)
    - name: Fastlane Action
      uses: maierj/fastlane-action@v1.4.0
      env:
        FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
        FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        MATCH_GITHUB_TOKEN: ${{ secrets.MATCH_GITHUB_TOKEN }}
        GITHUB_ACCESS_TOKEN: ${{ secrets.MATCH_GITHUB_TOKEN }}
      with:
       lane: ios production_upload version_number:${{ github.event.inputs.versionNumber }}
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.versionNumber }}
        release_name: Release-${{ github.event.inputs.versionNumber }}
        body: Release
        draft: false
        prerelease: false
    - name: Trigger DSYM
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: Upload DSYM
        token: ${{ secrets.GITHUB_TOKEN }}
