name: ShouldRun

defaults:
  run:
    shell: bash -ieo pipefail {0}

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}

jobs:
  should_run:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ inputs.path == 'Projects/App' || github.ref == 'refs/heads/main' || steps.changed-files.outputs.any_changed == 'true' }}

    steps:
      - uses: actions/checkout@v2
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v11.7
        with:
          files: |
            ${{ inputs.path }}
            Projects/Dependencies
            Projects/hCore
            Projects/hCoreUI
            Projects/hGraphQL
            Projects/ExampleUtil
            Projects/TestingUtil
            Projects/Testing
