name: SwiftFormat

on:
  pull_request:
    branches: ["*"]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: fwal/setup-swift@2040b795e5c453c3a05fcb8316496afc8a74f192
        with:
          swift-version: 5.9
      - name: Cache
        uses: actions/cache@v2
        with:
          path: build
          key: ${{ runner.os }}
      - name: Install Swift-Format
        run: scripts/install-swift-format.sh
      - name: Format
        run: scripts/format-ci.sh
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "Formatting"
          title: "Formatting: ${{ github.head_ref }}"
          body: "@${{ github.event.pull_request.user.login }} swift-format found changes that should be applied to your branch"
          branch: "formatting/${{ github.head_ref }}"
          base: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
