name: TestWorkspaceApp

defaults:
  run:
    shell: bash -ieo pipefail {0}

on:
  workflow_call:
    inputs:
      scheme:
        required: true
        type: string
    secrets:
      HEDVIG_GITHUB_APP_ID:
        required: true
      HEDVIG_GITHUB_APP_PRIVATE_KEY:
        required: true
      S3_ACCESS_KEY:
        required: true
      S3_SECRET_ACCESS_KEY:
        required: true

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 30
    steps:
      - name: Should run
        id: should_run
        uses: ./.github/actions/should-run
        with:
          path: ${{ inputs.path }}
      - uses: actions/checkout@v2
        if: steps.should_run.outputs.should_run == 'true'
      - uses: actions/download-artifact@v2
        with:
          name: generated_files
      - name: Bundle install
        run: arch -arm64 sudo --preserve-env bundle install
      - name: Fastlane Action
        env:
          FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: '180'
          FASTLANE_XCODE_LIST_TIMEOUT: '180'
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          HEDVIG_GITHUB_APP_ID: ${{ secrets.HEDVIG_GITHUB_APP_ID }}
          HEDVIG_GITHUB_APP_PRIVATE_KEY: ${{ secrets.HEDVIG_GITHUB_APP_PRIVATE_KEY }}
          GITHUB_JOB: test_${{ inputs.scheme }}
        run: arch -arm64 bundle exec fastlane ios test scheme:${{ inputs.scheme }}
      - name: Upload test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: Ugglan.xcresult
          path: fastlane/test_output/${{ inputs.scheme }}.xcresult

