name: Test

on:
  workflow_dispatch:
    inputs:
      versionNumber:
        description: "Version number"
        required: true

jobs:
  deploy:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "15.1"
      - name: Post checkout
        run: PATH=$PATH":$GITHUB_WORKSPACE/.tuist-bin" scripts/githooks.sh arch -x86_64 scripts/translations.sh scripts/swiftgen.sh scripts/codegen.sh
