name: UpdateLocalization

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  fetch-localization:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Fetch translations
        run: scripts/translations.sh
        env:
          LOKALIZE_TOKEN: ${{ secrets.LOKALIZE_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check for changes
        id: changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi
          echo "timestamp=$(date +'%Y-%m-%d-%H%M%S')" >> $GITHUB_OUTPUT
      - uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 # v1
        if: steps.changes.outputs.has_changes == 'true'
        with:
          xcode-version: latest-stable
      - name: Post checkout pre
        if: steps.changes.outputs.has_changes == 'true'
        run: scripts/install-tuist.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Post checkout
        if: steps.changes.outputs.has_changes == 'true'
        run: scripts/post-checkout.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build project
        if: steps.changes.outputs.has_changes == 'true'
        run: xcodebuild build -workspace Ugglan.xcworkspace -scheme Ugglan -destination 'generic/platform=iOS Simulator' CODE_SIGNING_ALLOWED=NO
      - name: Create Pull Request
        if: steps.changes.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: Updated translations ${{ steps.changes.outputs.timestamp }}"
          committer: hedvig-ops-bot <infra@hedvig.com>
          author: hedvig-ops-bot <infra@hedvig.com>
          branch: "chore/update-translations-${{ steps.changes.outputs.timestamp }}"
          title: "chore: Update translations ${{ steps.changes.outputs.timestamp }}"
          body: "Automated translation update"
