name: Upload DSYM

on: [workflow_dispatch]

jobs:
  upload-dsym:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Bundle install
      run: arch -arm64 sudo --preserve-env bundle install
    - run: brew install node
    - run: npm install -g @datadog/datadog-ci
    - name: Fastlane Action
      env:
        FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
        APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
        APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
        APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
        DOWNLOAD_DSYMS_APP_IDENTIFIER: ${{ secrets.DOWNLOAD_DSYMS_APP_IDENTIFIER }}
        DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
        DOWNLOAD_DSYMS_MIN_VERSION: ${{ secrets.DOWNLOAD_DSYMS_MIN_VERSION }}
      run: arch -arm64 bundle exec fastlane ios upload_dsyms