name: Upload DSYM

on: [workflow_dispatch]

jobs:
  upload-dsym:
    runs-on: macos-latest

    steps:
    - name: Wait 30 minutes for App Store processing
      uses: jakejarvis/wait-action@master
      with:
        time: '30m'
    - uses: actions/checkout@v2
    - run: brew install getsentry/tools/sentry-cli
    - name: Fastlane Action
      uses: maierj/fastlane-action@v1.4.0
      env:
       FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
       FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
       DOWNLOAD_DSYMS_APP_IDENTIFIER: ${{ secrets.DOWNLOAD_DSYMS_APP_IDENTIFIER }}
       SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
       SENTRY_PROJECT_SLUG: ${{ secrets.SENTRY_PROJECT_SLUG }}
       SENTRY_ORG_SLUG: ${{ secrets.SENTRY_ORG_SLUG }}
       DOWNLOAD_DSYMS_MIN_VERSION: ${{ secrets.DOWNLOAD_DSYMS_MIN_VERSION }}
      with:
       lane: ios upload_dsyms_to_sentry
