name: Upload DSYM

on: [workflow_dispatch]

jobs:
  upload-dsym:
    runs-on: MachineOne

    steps:
    - uses: actions/checkout@v2
    - name: Bundle install
      run: arch -arm64 sudo --preserve-env bundle install
    - name: Fastlane Action
      env:
        FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
        FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
        FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
        DOWNLOAD_DSYMS_APP_IDENTIFIER: ${{ secrets.DOWNLOAD_DSYMS_APP_IDENTIFIER }}
        DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
        DOWNLOAD_DSYMS_MIN_VERSION: ${{ secrets.DOWNLOAD_DSYMS_MIN_VERSION }}
      run: arch -arm64 bundle exec fastlane ios upload_dsyms