name: WorkspaceApps

defaults:
  run:
    shell: bash -ieo pipefail {0}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: ['*']

jobs:
  generate:
    runs-on: self-hosted
    
    steps:
    - name: Post checkout
      run: sh scripts/post-checkout.sh
    - name: Upload generated files
      uses: actions/upload-artifact@v2
      with:
        name: generated_files
        path: |
          *.xcworkspace
          **/*.xcodeproj
          **/Derived/**/*.swift
          **/Derived/**/*.plist
          **/Resources/*.lproj
  build_ugglan:
    runs-on: self-hosted
    needs: [generate]

    steps:
    - uses: ./.github/actions/BuildWorkspaceApp
      with:
        identifier: com.hedvig.test.app
        path: Projects/App/Ugglan.xcodeproj
        scheme: Ugglan
  build_embark:
    runs-on: self-hosted
    needs: [generate]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: generated_files
    - uses: ./.github/actions/FastlaneAction
      with:
        lane: ios build path:Projects/Embark/Embark.xcodeproj scheme:EmbarkExample
    - name: Upload app
      uses: actions/upload-artifact@v2
      with:
        name: EmbarkExample.ipa
        path: fastlane/build_output/EmbarkExample.ipa
  build_hedvig:
    runs-on: self-hosted
    needs: [generate]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: generated_files
    - uses: ./.github/actions/FastlaneAction
      with:
        lane: ios build identifier:com.hedvig.app path:Projects/App/Ugglan.xcodeproj scheme:Hedvig
    - name: Upload app
      uses: actions/upload-artifact@v2
      with:
        name: Hedvig.ipa
        path: fastlane/build_output/Hedvig.ipa
  build_home:
    runs-on: self-hosted
    needs: [generate]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: generated_files
    - uses: ./.github/actions/FastlaneAction
      with:
        lane: ios build path:Projects/Home/Home.xcodeproj scheme:HomeExample
    - name: Upload app
      uses: actions/upload-artifact@v2
      with:
        name: HomeExample.ipa
        path: fastlane/build_output/HomeExample.ipa
  build_forever:
    runs-on: self-hosted
    needs: [generate]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: generated_files
    - uses: ./.github/actions/FastlaneAction
      with:
        lane: ios build path:Projects/Forever/Forever.xcodeproj scheme:ForeverExample
    - name: Upload app
      uses: actions/upload-artifact@v2
      with:
        name: ForeverExample.ipa
        path: fastlane/build_output/ForeverExample.ipa
  build_offer:
    runs-on: self-hosted
    needs: [generate]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: generated_files
    - uses: ./.github/actions/FastlaneAction
      with:
        lane: ios build path:Projects/Offer/Offer.xcodeproj scheme:OfferExample
    - name: Upload app
      uses: actions/upload-artifact@v2
      with:
        name: OfferExample.ipa
        path: fastlane/build_output/OfferExample.ipa
  build_hcoreui:
    runs-on: self-hosted
    needs: [generate]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: generated_files
    - uses: ./.github/actions/FastlaneAction
      with:
        lane: ios build path:Projects/hCoreUI/hCoreUI.xcodeproj scheme:hCoreUIExample
    - name: Upload app
      uses: actions/upload-artifact@v2
      with:
        name: hCoreUIExample.ipa
        path: fastlane/build_output/hCoreUIExample.ipa
  slack:
    runs-on: ubuntu-latest
    needs: [build_ugglan, build_embark, build_hedvig, build_home, build_forever, build_offer, build_hcoreui]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: fastlane/build_output
      - name: Fastlane Action
        uses: maierj/fastlane-action@v1.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          SLACK_IOS_BUILDS_URL: ${{ secrets.SLACK_IOS_BUILDS_URL }}
          SLACK_IOS_PR_BUILDS_URL: ${{ secrets.SLACK_IOS_PR_BUILDS_URL }}
          BRANCH_NAME: ${{ github.head_ref }}
          GITHUB_PR_NUMBER: ${{ github.event.number }}
          FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: '180'
          FASTLANE_XCODE_LIST_TIMEOUT: '180'
        with:
          lane: ios slack_message

