name: WorkspaceApps

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: XCode Select
      run: sudo xcode-select -s /Applications/Xcode_11.6.app
    - name: Cache RubyGems
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: ${{ runner.os }}-gem-
    - uses: actions/cache@v1
      with:
        path: gym_derived_data
        key: ${{ runner.os }}-gym-derived-data
    - uses: actions/cache@v1
      with:
        path: Carthage
        key: ${{ runner.os }}-xcode-11.6-carthage-${{ hashFiles('**/Cartfile.resolved') }}
    - name: Install Tuist
      run: bash <(curl -Ls https://install.tuist.io)
    - name: Fastlane Action
      uses: maierj/fastlane-action@v1.4.0
      env:
        FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
        FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        MATCH_GITHUB_TOKEN: ${{ secrets.MATCH_GITHUB_TOKEN }}
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
        S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
        SLACK_URL: ${{ secrets.SLACK_URL }}
      with:
       lane: ios workspace_apps
    - name: Upload built apps
      uses: actions/upload-artifact@v2
      with:
        name: apps
        path: fastlane/build_output
