name: WorkspaceTests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: ['*']

jobs:
  test:
    runs-on: self-hosted

    steps:
    - name: Cleanup
      run: sudo rm -rf *
    - uses: actions/checkout@v2
    - name: Bundle install
      run: arch -arm64 sudo bundle install
    - name: Fastlane Action
      env:
        CI: 'true'
        APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
        APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
        APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
        GITHUB_ACCESS_TOKEN: ${{ secrets.MATCH_GITHUB_TOKEN }}
        FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: '180'
        FASTLANE_XCODE_LIST_TIMEOUT: '180'
      run: arch -arm64 sudo bundle exec fastlane ios workspace_tests
    - name: Upload test results
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: test_output
        path: fastlane/test_output
    - name: Upload test results html
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: test_output.html
        path: fastlane/test_output/index.html
