name: WorkspaceApps

defaults:
  run:
    shell: bash -ieo pipefail {0}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: ['*']

jobs:
  generate:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2
    - name: Post checkout
      run: sh scripts/post-checkout.sh
    - name: Upload generated
      run: rsync -rav --include="*/" --include='*.xcworkspace/**' --include='*.xcodeproj/**' --include='*.xcworkspace' --include='*.xcodeproj' --include='**/Derived/**.plist' --include='**/Resources/**.lproj' --include='**/Resources/**.lproj/**'  --include='**/Derived/**.swift' --exclude='*' . ${{ secrets.SSH_CACHE_CREDENTIALS }}:/Volumes/Cache/generated/${{ github.sha }}
  ugglan:
    needs: [generate]
    uses: HedvigInsurance/ugglan/.github/workflows/BuildWorkspaceApp.yml@only-run-if-changed
    with:
      lane: ios build identifier:com.hedvig.test.app path:Projects/App/Ugglan.xcodeproj scheme:Ugglan
      name: Ugglan
      path: Projects/App
      test_scheme: Ugglan
    secrets:
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      MATCH_GITHUB_TOKEN: ${{ secrets.MATCH_GITHUB_TOKEN }}
      HEDVIG_GITHUB_APP_ID: ${{ secrets.HEDVIG_GITHUB_APP_ID }}
      HEDVIG_GITHUB_APP_PRIVATE_KEY: ${{ secrets.HEDVIG_GITHUB_APP_PRIVATE_KEY }}
      S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
      S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
      SSH_CACHE_CREDENTIALS: ${{ secrets.SSH_CACHE_CREDENTIALS }}
  embark:
    needs: [generate]
    uses: HedvigInsurance/ugglan/.github/workflows/BuildWorkspaceApp.yml@only-run-if-changed
    with:
      lane: ios build path:Projects/Embark/Embark.xcodeproj scheme:EmbarkExample
      name: EmbarkExample
      path: Projects/Embark
      test_scheme: Embark
    secrets:
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      MATCH_GITHUB_TOKEN: ${{ secrets.MATCH_GITHUB_TOKEN }}
      HEDVIG_GITHUB_APP_ID: ${{ secrets.HEDVIG_GITHUB_APP_ID }}
      HEDVIG_GITHUB_APP_PRIVATE_KEY: ${{ secrets.HEDVIG_GITHUB_APP_PRIVATE_KEY }}
      S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
      S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
      SSH_CACHE_CREDENTIALS: ${{ secrets.SSH_CACHE_CREDENTIALS }}
  hedvig:
    needs: [generate]
    uses: HedvigInsurance/ugglan/.github/workflows/BuildWorkspaceApp.yml@only-run-if-changed
    with:
      lane: ios build identifier:com.hedvig.app path:Projects/App/Ugglan.xcodeproj scheme:Hedvig
      name: Hedvig
      path: Projects/App
    secrets:
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      MATCH_GITHUB_TOKEN: ${{ secrets.MATCH_GITHUB_TOKEN }}
      HEDVIG_GITHUB_APP_ID: ${{ secrets.HEDVIG_GITHUB_APP_ID }}
      HEDVIG_GITHUB_APP_PRIVATE_KEY: ${{ secrets.HEDVIG_GITHUB_APP_PRIVATE_KEY }}
      S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
      S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
      SSH_CACHE_CREDENTIALS: ${{ secrets.SSH_CACHE_CREDENTIALS }}
  home:
    needs: [generate]
    uses: HedvigInsurance/ugglan/.github/workflows/BuildWorkspaceApp.yml@only-run-if-changed
    with:
      lane: ios build path:Projects/Home/Home.xcodeproj scheme:HomeExample
      name: HomeExample
      path: Projects/Home
      test_scheme: Home
    secrets:
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      MATCH_GITHUB_TOKEN: ${{ secrets.MATCH_GITHUB_TOKEN }}
      HEDVIG_GITHUB_APP_ID: ${{ secrets.HEDVIG_GITHUB_APP_ID }}
      HEDVIG_GITHUB_APP_PRIVATE_KEY: ${{ secrets.HEDVIG_GITHUB_APP_PRIVATE_KEY }}
      S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
      S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
      SSH_CACHE_CREDENTIALS: ${{ secrets.SSH_CACHE_CREDENTIALS }}
  forever:
    needs: [generate]
    uses: HedvigInsurance/ugglan/.github/workflows/BuildWorkspaceApp.yml@only-run-if-changed
    with:
      lane: ios build path:Projects/Forever/Forever.xcodeproj scheme:ForeverExample
      name: ForeverExample
      path: Projects/Forever
      test_scheme: Forever
    secrets:
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      MATCH_GITHUB_TOKEN: ${{ secrets.MATCH_GITHUB_TOKEN }}
      HEDVIG_GITHUB_APP_ID: ${{ secrets.HEDVIG_GITHUB_APP_ID }}
      HEDVIG_GITHUB_APP_PRIVATE_KEY: ${{ secrets.HEDVIG_GITHUB_APP_PRIVATE_KEY }}
      S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
      S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
      SSH_CACHE_CREDENTIALS: ${{ secrets.SSH_CACHE_CREDENTIALS }}
  offer:
    needs: [generate]
    uses: HedvigInsurance/ugglan/.github/workflows/BuildWorkspaceApp.yml@only-run-if-changed
    with:
      lane: ios build path:Projects/Offer/Offer.xcodeproj scheme:OfferExample
      name: OfferExample
      path: Projects/Offer
      test_scheme: Offer
    secrets:
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      MATCH_GITHUB_TOKEN: ${{ secrets.MATCH_GITHUB_TOKEN }}
      HEDVIG_GITHUB_APP_ID: ${{ secrets.HEDVIG_GITHUB_APP_ID }}
      HEDVIG_GITHUB_APP_PRIVATE_KEY: ${{ secrets.HEDVIG_GITHUB_APP_PRIVATE_KEY }}
      S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
      S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
      SSH_CACHE_CREDENTIALS: ${{ secrets.SSH_CACHE_CREDENTIALS }}
  hcoreui:
    needs: [generate]
    uses: HedvigInsurance/ugglan/.github/workflows/BuildWorkspaceApp.yml@only-run-if-changed
    with:
      lane: ios build path:Projects/hCoreUI/hCoreUI.xcodeproj scheme:hCoreUIExample
      name: hCoreUIExample
      path: Projects/hCoreUI
      test_scheme: hCoreUI
    secrets:
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      MATCH_GITHUB_TOKEN: ${{ secrets.MATCH_GITHUB_TOKEN }}
      HEDVIG_GITHUB_APP_ID: ${{ secrets.HEDVIG_GITHUB_APP_ID }}
      HEDVIG_GITHUB_APP_PRIVATE_KEY: ${{ secrets.HEDVIG_GITHUB_APP_PRIVATE_KEY }}
      S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
      S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
      SSH_CACHE_CREDENTIALS: ${{ secrets.SSH_CACHE_CREDENTIALS }}
  slack:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - ugglan
      - embark
      - hedvig
      - home
      - forever
      - offer
      - hcoreui
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: fastlane/build_output
      - name: Fastlane Action
        uses: maierj/fastlane-action@v1.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          SLACK_IOS_BUILDS_URL: ${{ secrets.SLACK_IOS_BUILDS_URL }}
          SLACK_IOS_PR_BUILDS_URL: ${{ secrets.SLACK_IOS_PR_BUILDS_URL }}
          BRANCH_NAME: ${{ github.head_ref }}
          GITHUB_PR_NUMBER: ${{ github.event.number }}
          FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: '180'
          FASTLANE_XCODE_LIST_TIMEOUT: '180'
        with:
          lane: ios slack_message

