name: WorkspaceTests

defaults:
  run:
    shell: bash -ieo pipefail {0}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: ['*']

jobs:
  test_ugglan:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Bundle install
      run: arch -arm64 sudo --preserve-env bundle install
    - name: Fastlane Action
      env:
        FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: '180'
        FASTLANE_XCODE_LIST_TIMEOUT: '180'
      run: arch -arm64 bundle exec fastlane ios test scheme:Ugglan
    - name: Upload test results
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: Ugglan.xcresult
        path: fastlane/test_output/Ugglan.xcresult
  test_hCore:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Bundle install
      run: arch -arm64 sudo --preserve-env bundle install
    - name: Fastlane Action
      env:
        FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: '180'
        FASTLANE_XCODE_LIST_TIMEOUT: '180'
      run: arch -arm64 bundle exec fastlane ios test scheme:hCore
    - name: Upload test results
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: hCore.xcresult
        path: fastlane/test_output/hCore.xcresult
  test_hCoreUI:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Bundle install
      run: arch -arm64 sudo --preserve-env bundle install
    - name: Fastlane Action
      env:
        FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: '180'
        FASTLANE_XCODE_LIST_TIMEOUT: '180'
      run: arch -arm64 bundle exec fastlane ios test scheme:hCoreUI
    - name: Upload test results
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: hCoreUI.xcresult
        path: fastlane/test_output/hCoreUI.xcresult
  test_forever:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Bundle install
      run: arch -arm64 sudo --preserve-env bundle install
    - name: Fastlane Action
      env:
        FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: '180'
        FASTLANE_XCODE_LIST_TIMEOUT: '180'
      run: arch -arm64 bundle exec fastlane ios test scheme:Forever
    - name: Upload test results
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: Forever.xcresult
        path: fastlane/test_output/Forever.xcresult
  test_contracts:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Bundle install
      run: arch -arm64 sudo --preserve-env bundle install
    - name: Fastlane Action
      env:
        FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: '180'
        FASTLANE_XCODE_LIST_TIMEOUT: '180'
      run: arch -arm64 bundle exec fastlane ios test scheme:Contracts
    - name: Upload test results
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: Contracts.xcresult
        path: fastlane/test_output/Contracts.xcresult
  test_home:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Bundle install
      run: arch -arm64 sudo --preserve-env bundle install
    - name: Fastlane Action
      env:
        FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: '180'
        FASTLANE_XCODE_LIST_TIMEOUT: '180'
      run: arch -arm64 bundle exec fastlane ios test scheme:Home
    - name: Upload test results
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: Home.xcresult
        path: fastlane/test_output/Home.xcresult
