name: WorkspaceApps

defaults:
  run:
    shell: bash -ieo pipefail {0}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: ['*']

jobs:
  generate:
    runs-on: self-hosted
    
    steps:
    - name: Post checkout
      run: sh scripts/post-checkout.sh
    - name: Upload generated files
      uses: actions/upload-artifact@v2
      with:
        name: generated_files
        path: |
          *.xcworkspace
          **/*.xcodeproj
          **/Derived/**/*.swift
          **/Derived/**/*.plist
          **/Resources/*.lproj
  build_ugglan:
    needs: [generate]
    uses: HedvigInsurance/ugglan/.github/workflows/BuildWorkspaceApp.yml@ci-generate-before
    with:
      lane: ios build path:Projects/App/Ugglan.xcodeproj scheme:Ugglan
      name: Ugglan
    secrets:
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      MATCH_GITHUB_TOKEN: ${{ secrets.MATCH_GITHUB_TOKEN }}
      HEDVIG_GITHUB_APP_ID: ${{ secrets.HEDVIG_GITHUB_APP_ID }}
      HEDVIG_GITHUB_APP_PRIVATE_KEY: ${{ secrets.HEDVIG_GITHUB_APP_PRIVATE_KEY }}
      S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
      S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
  build_embark:
    needs: [generate]
    uses: HedvigInsurance/ugglan/.github/workflows/BuildWorkspaceApp.yml@ci-generate-before
    with:
      lane: ios build path:Projects/Embark/Embark.xcodeproj scheme:EmbarkExample
      name: EmbarkExample
    secrets:
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      MATCH_GITHUB_TOKEN: ${{ secrets.MATCH_GITHUB_TOKEN }}
      HEDVIG_GITHUB_APP_ID: ${{ secrets.HEDVIG_GITHUB_APP_ID }}
      HEDVIG_GITHUB_APP_PRIVATE_KEY: ${{ secrets.HEDVIG_GITHUB_APP_PRIVATE_KEY }}
      S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
      S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
  slack:
    runs-on: ubuntu-latest
    needs: [build_ugglan, build_embark]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: fastlane/build_output
      - name: Fastlane Action
        uses: maierj/fastlane-action@v1.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          SLACK_IOS_BUILDS_URL: ${{ secrets.SLACK_IOS_BUILDS_URL }}
          SLACK_IOS_PR_BUILDS_URL: ${{ secrets.SLACK_IOS_PR_BUILDS_URL }}
          BRANCH_NAME: ${{ github.head_ref }}
          GITHUB_PR_NUMBER: ${{ github.event.number }}
          FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: '180'
          FASTLANE_XCODE_LIST_TIMEOUT: '180'
        with:
          lane: ios slack_message

