name: WorkspaceTestsRecord

defaults:
  run:
    shell: bash -ieo pipefail {0}

on:
  workflow_dispatch:
    inputs:
      schemeFilter:
        description: 'Schemes'
        required: false

jobs:
  test:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Bundle install
      run: arch -arm64 sudo --preserve-env bundle install
    - name: Fastlane Action
      env:
        APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
        APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
        APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
        GITHUB_ACCESS_TOKEN: ${{ secrets.MATCH_GITHUB_TOKEN }}
        FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: '180'
        FASTLANE_XCODE_LIST_TIMEOUT: '180'
      run: SCHEME_FILTER=${{ github.event.inputs.schemeFilter }} RECORD=true arch -arm64 bundle exec fastlane ios workspace_tests
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: 'Update WorkspaceTests snapshots'
        title: 'Update WorkspaceTests snapshots'
        body: 'This PR was created automatically by the ProductionDeploy action, merge this so that the repo has a matching app version to what will be deployed to App Store.'
        branch: 'update-snapshots/${{ github.run_id }}/${{ github.run_number }}'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
