name: WorkspaceApps

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: XCode Select
      run: sudo xcode-select -s /Applications/Xcode_11.6.app
    - name: Cache Tuist
      uses: actions/cache@v1
      with:
        path: .tuist/Cache
        key: ${{ runner.os }}-tuist
    - uses: actions/cache@v1
      with:
        path: ~/Library/Developer/Xcode/DerivedData
        key: ${{ runner.os }}-derived-data
    - uses: actions/cache@v1
      with:
        path: Carthage
        key: ${{ runner.os }}-xcode-11.6-carthage-${{ hashFiles('**/Cartfile.resolved') }}
    - uses: jwalton/gh-find-current-pr@v1
      id: findPr
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install Tuist
      run: bash <(curl -Ls https://install.tuist.io)
    - name: Fastlane Action
      uses: maierj/fastlane-action@v1.4.0
      env:
        FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
        FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        MATCH_GITHUB_TOKEN: ${{ secrets.MATCH_GITHUB_TOKEN }}
        GITHUB_ACCESS_TOKEN: ${{ secrets.MATCH_GITHUB_TOKEN }}
        S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
        S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
        SLACK_IOS_BUILDS_URL: ${{ secrets.SLACK_IOS_BUILDS_URL }}
        SLACK_IOS_PR_BUILDS_URL: ${{ secrets.SLACK_IOS_PR_BUILDS_URL }}
        BRANCH_NAME: ${{ github.head_ref }}
        GITHUB_PR_NUMBER: ${{ steps.findPr.outputs.pr }}
      with:
       lane: ios workspace_apps
